import {
  Gauge, Users, GraduationCap, UserCheck, ClipboardCheck, TrendingUp,
  ArrowDown, AlertCircle, Wallet, Banknote, ArrowLeftRight, Bell,
  Inbox, Loader2, LogIn, Eye, EyeOff, LogOut, Settings as SettingsIcon,
  HandCoins, Receipt, Coins, Book, CalendarCheck, FileText, Megaphone,
  BookOpen, BarChart3, CalendarDays, Plus, Save, Pencil, Trash2, Check,
  X, Search, Download, Upload, Printer, Share2, Undo2, History,
  CheckCircle, UserPlus, Send, Lock, KeyRound, Building2, PlusCircle,
  Keyboard, Trophy, ChevronDown, School, Calendar, ArrowUp, User,
  BookOpenCheck, Calculator, Layers, Clock, RefreshCw, Info, Shield, Link, XCircle, PieChart, Pin, Baby, CalendarMinus, CheckCheck, ListChecks,
  MessageCircle, Phone, Fingerprint, Wifi, WifiOff, ScanLine, ArrowRightLeft,
  Zap, Scale, IdCard, ContactRound, Bed, Package, LayoutGrid, Scroll, ClipboardList, GraduationCap as ChalkboardTeacher, ReceiptText, Filter,
  List, Flame, ArrowLeft, Tags,
  Home, MoreHorizontal, Pen, Mail, LockOpen, Palette, Plug, RotateCcw,
  UserCircle, UserCog, UserX, CircleArrowDown, CircleArrowUp,
  MessageSquare, Smartphone, UserRoundPen,
  type LucideIcon
} from "lucide-react";
import { cn } from "@/lib/utils";

const iconMap: Record<string, LucideIcon> = {
  "fa-tachometer-alt": Gauge,
  "fa-users": Users,
  "fa-user-graduate": GraduationCap,
  "fa-user-check": UserCheck,
  "fa-clipboard-check": ClipboardCheck,
  "fa-chart-line": TrendingUp,
  "fa-arrow-down": ArrowDown,
  "fa-arrow-up": ArrowUp,
  "fa-exclamation-circle": AlertCircle,
  "fa-wallet": Wallet,
  "fa-money-bill-wave": Banknote,
  "fa-exchange-alt": ArrowLeftRight,
  "fa-bell": Bell,
  "fa-inbox": Inbox,
  "fa-spinner": Loader2,
  "fa-sign-in-alt": LogIn,
  "fa-eye": Eye,
  "fa-eye-slash": EyeOff,
  "fa-sign-out-alt": LogOut,
  "fa-cog": SettingsIcon,
  "fa-hand-holding-usd": HandCoins,
  "fa-money-check-alt": Receipt,
  "fa-coins": Coins,
  "fa-book": Book,
  "fa-book-open": BookOpen,
  "fa-book-reader": BookOpenCheck,
  "fa-calendar-check": CalendarCheck,
  "fa-file-invoice-dollar": FileText,
  "fa-file-alt": FileText,
  "fa-file-pdf": FileText,
  "fa-bullhorn": Megaphone,
  "fa-chart-bar": BarChart3,
  "fa-calendar-alt": CalendarDays,
  "fa-calendar": Calendar,
  "fa-plus": Plus,
  "fa-plus-circle": PlusCircle,
  "fa-save": Save,
  "fa-edit": Pencil,
  "fa-trash": Trash2,
  "fa-check": Check,
  "fa-check-circle": CheckCircle,
  "fa-times": X,
  "fa-search": Search,
  "fa-download": Download,
  "fa-upload": Upload,
  "fa-print": Printer,
  "fa-share": Share2,
  "fa-undo": Undo2,
  "fa-history": History,
  "fa-user-plus": UserPlus,
  "fa-paper-plane": Send,
  "fa-lock": Lock,
  "fa-key": KeyRound,
  "fa-mosque": Building2,
  "fa-graduation-cap": GraduationCap,
  "fa-chalkboard": School,
  "fa-keyboard": Keyboard,
  "fa-trophy": Trophy,
  "fa-chevron-down": ChevronDown,
  "fa-university": School,
  "fa-user-tie": User,
  "fa-user-clock": AlertCircle,
  "fa-list-alt": FileText,
  "fa-calculator": Calculator,
  "fa-layer-group": Layers,
  "fa-clock": Clock,
  "fa-sync": RefreshCw,
  "fa-info-circle": Info,
  "fa-user-shield": Shield,
  "fa-link": Link,
  "fa-times-circle": XCircle,
  "fa-chart-pie": PieChart,
  "fa-thumbtack": Pin,
  "fa-child": Baby,
  "fa-exclamation-triangle": AlertCircle,
  "fa-calendar-minus": CalendarMinus,
  "fa-check-double": CheckCheck,
  "fa-list-check": ListChecks,
  "fa-whatsapp": MessageCircle,
  "fa-phone": Phone,
  "fa-fingerprint": Fingerprint,
  "fa-wifi": Wifi,
  "fa-wifi-off": WifiOff,
  "fa-scan": ScanLine,
  "fa-map": ArrowRightLeft,
  "fa-bolt": Zap,
  "fa-balance-scale": Scale,
  "fa-id-card": IdCard,
  "fa-tasks": ListChecks,
  "fa-address-card": ContactRound,
  "fa-bed": Bed,
  "fa-boxes": Package,
  "fa-th-large": LayoutGrid,
  "fa-scroll": Scroll,
  "fa-clipboard-list": ClipboardList,
  "fa-chalkboard-teacher": ChalkboardTeacher,
  "fa-receipt": ReceiptText,
  "fa-filter": Filter,
  "fa-list": List,
  "fa-fire": Flame,
  "fa-arrow-left": ArrowLeft,
  "fa-tags": Tags,
  /* ── newly added ── */
  "fa-home": Home,
  "fa-ellipsis-h": MoreHorizontal,
  "fa-pen-fancy": Pen,
  "fa-envelope": Mail,
  "fa-lock-open": LockOpen,
  "fa-palette": Palette,
  "fa-plug": Plug,
  "fa-trash-alt": Trash2,
  "fa-trash-restore": RotateCcw,
  "fa-user-circle": UserCircle,
  "fa-users-cog": UserCog,
  "fa-users-slash": UserX,
  "fa-user-edit": UserRoundPen,
  "fa-comment-alt": MessageSquare,
  "fa-comments": MessageSquare,
  "fa-sms": Smartphone,
  "fa-arrow-circle-down": CircleArrowDown,
  "fa-arrow-circle-up": CircleArrowUp,
  "fa-building": Building2,
  "fa-id-badge": IdCard,
};

interface IconProps {
  name: string;
  size?: number;
  className?: string;
  style?: React.CSSProperties;
}

export default function Icon({ name, size = 16, className, style }: IconProps) {
  const cleanName = name.replace(/^fas\s+/, "").replace(/^far\s+/, "").replace(/^fab\s+/, "");
  const isSpin = name.includes("fa-spin");
  const LucideIcon = iconMap[cleanName];
  if (!LucideIcon) return null;
  return (
    <LucideIcon
      size={size}
      className={cn(isSpin && "animate-spin", className)}
      style={{ display: "inline", verticalAlign: "middle", ...style }}
    />
  );
}
